export enum EMPLOYEE_DETAIL_TAB {
	PERSONAL_INFORMATION = 'PERSONAL_INFORMATION',
	WORK_INFORMATION = 'WORK_INFORMATION',
	SALARY_INFORMATION = 'SALARY_INFORMATION',
	CONTRACT_INFORMATION = 'CONTRACT_INFORMATION',
	INSURANCE_INFORMATION = 'INSURANCE_INFORMATION',
	BANK_INFORMATION = 'BANK_INFORMATION',
	ATTENDANCE_HISTORY = 'ATTENDANCE_HISTORY',
	LEAVE_HISTORY = 'LEAVE_HISTORY',
	PERFORMANCE = 'PERFORMANCE',
	ASSET = 'ASSET',
	TRAINING = 'TRAINING',
	HISTORY = 'HISTORY',
}
